dist: xenial
arch: 
  - arm64
language: 
  - c
compiler: 
  - gcc
services:
  - docker
script: 
  - echo "Starting build-task"
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - travis_wait make build-istio