dist: xenial
arch: 
  - arm64
language: c
sudo: false
compiler: 
  - gcc
services:
  - docker
install:
  - echo "Starting install-task"
script: 
  - echo "Start make-task"
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - travis_wait make build-istio