dist: bionic
arch: 
  - arm64
language: c
sudo: true
env:
  global:
  - ISTIO_VERSION=1.6.12
  - HUB=istioarm64
  - TAG=${ISTIO_VERSION}-${TRAVIS_CPU_ARCH}
services:
  - docker
script: 
  - while sleep 9m; do ps aux; echo "=====[ $SECONDS seconds still running ]====="; done &
  - make build-istio
  - kill %1