dist: xenial
arch: arm64
language: c
sudo: false
compiler: gcc
services:
  - docker
install: skip
script: echo "Start make-task" && docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} && make build-istio