dist: bionic
arch: 
  - arm64
language: 
  - c
compiler: 
  - gcc
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
  - echo "Starting install-task"
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
script: 
  - travis_wait make build-istio