dist: focal
arch: 
  - arm64
language: 
  - c
compiler: 
  - gcc
services:
  - docker
install:
  - echo "Starting install-task"
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
script: 
  - travis_wait make build-istio