# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.1.0
      - name: docker-login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.HUB_SERVER }}
      - name: Run a multi-line script
        run: |
          ISTIO_VERSION=1.7.4 HUB=${{ secrets.HUB }} TAG=$ISTIO_VERSION BAZEL_BUILD_ARGS="--jobs 1" make build-istio
          make cleanup
